language: php
php:
    - 7.1
    - 7.2
dist: trusty
cache:
    directories:
        - $HOME/.composer/cache
before_install:
    - 'composer self-update'
    - 'composer --version'
    - 'composer install --no-interaction'
    - './vendor/bin/hidev --version'
    - './vendor/bin/hidev travis/before-install'
sudo: false
install:
    - './vendor/bin/hidev travis/install'
script:
    - './vendor/bin/hidev travis/script'
after_script:
    - './vendor/bin/hidev travis/after-script'
